version: "3.9"
services:
  postgresql:
    image: "postgres:14.2-alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "local"
